DB_NAME="mmusafiri98's Project"                # Nom de ta base
DB_USER="postgres"                       # User affiché
DB_PASS="[8A%/pB7^Kt2]"          # Mot de passe que tu as choisi
DB_HOST="2a05:d016:571:a403:cc8b:4d74:a64d:65cf"    # Host réel trouvé dans Connection info
DB_PORT="5432"                            # Port par défaut
